### PR TITLE
Modernize setuptools bootstrap script

### PR DESCRIPTION
**Pull request by lpsinger**
The old `distribute_setup.py` bootstrap script does not even work any more, because an exception is raised when it makes a request from PyPI using a non-https URL (`urllib.error.HTTPError: HTTP Error 403: SSL is required`). This made it impossible to install pyxmpp2 using pip.

Switch to using the latest bootstrap script `ez_setup.py` from the modern Setuptools project.

### CODE REVIEW

**Comment by Jajcus** [comment]
Thank you for your contribution.

I am all in favour of removing `distribute_setup.py`, but the included `ez_setup.py` script states in its description:

> This method is DEPRECATED. Check https://github.com/pypa/setuptools/issues/581 for more details.

I don't think we should use it. Instead, we should just modernize `setup.py`, removing all traces of `distribute`.

**Comment by lpsinger** [comment]
OK, I updated the PR accordingly.

**Comment by Jajcus** [comment]
Now the PR also adds pyproject.toml file with now information about it in the commit. In fact I have just learned about PEP 518 right now.  I don't think we need it. As added, it contains the defaults tools should use any way. And I don't think 'wheel' is actually needed now to build PyXMPP2.

I would also prefer the change as a single commit – could you squash the two commits into one? The only thing left will probably be removal of ez_setup and distribute import from setup.py.

**Comment by Jajcus** [comment]
Merged, thanks.

I'll try to make a release this weekend. I have mixed feelings, as PyXMPP is a bit abandoned now, but if it works and there are people interested, I can push this as a new 'release'.

**Comment by lpsinger** [comment]
> I'll try to make a release this weekend. I have mixed feelings, as PyXMPP is a bit abandoned now, but if it works and there are people interested, I can push this as a new 'release'.

[We still use pyxmpp](https://git.ligo.org/lscsoft/lvalert) in the [LIGO and Virgo gravitational-wave observatories](http://ligo.org), although we have been looking at more modern alternatives. It would be very nice to get a new release of pyxmpp2 that works with pip so that we have a Python 3 compatible xmpp library if we end up sticking with xmpp for our next observing run.

**Comment by Jajcus** [comment]
> We still use pyxmpp in the LIGO and Virgo gravitational-wave observatories,

Wow! Then I will make the release soon. :-)

**Comment by Jajcus** [comment]
Done.

**Comment by lpsinger** [comment]
Thank you! As you can see I'm already using this.

**Pull request merged**
